In [1]:
import numpy as np

## Numpy 는 숫자 데이터를 가공하고 행렬계산을 하는데 사용하는 파이썬 모듈입니다.
### Numpy 로 하는 일
1. List 자료로 Numpy array 로 만들기
2. 행렬 형태 확인하기
3. 행렬 형태 바꾸기
4. 행렬 데이터 만들기
5. 행렬의 일부 구간 추출하기
6. 행렬끼리 더하기, 곱하기, 행렬 원소간의 연산
7. 행렬끼리 합치기
8. 그외 연산

### 1. List 자료로 Numpy array 만들기 : array()

In [6]:
a = [1, 2, 3]    
print(type(a))
A = np.array(a)

print('Numpy array A :', A)
print('Type :', type(A))

A = np.array(a, dtype='float')     #데이터 타입을 float 로 캐스팅해서 배열로 만들기
print('Numpy array A (float) :', A)

type(A)

<class 'list'>
Numpy array A : [1 2 3]
Type : <class 'numpy.ndarray'>
Numpy array A (float) : [1. 2. 3.]


numpy.ndarray

### 일반 Boolean 타입의 리스트를 배열로 만들기 : astype( )

In [10]:
b = [True, False, True]
print(type(b))
B = np.array(b)

print('Numpy array B :', B)
print('Numpy array B (int) :', B.astype(int))
print(type(B))

<class 'list'>
Numpy array B : [ True False  True]
Numpy array B (int) : [1 0 1]
<class 'numpy.ndarray'>


### 2차원 리스트를 배열로 만들기

In [16]:
c = [[1,2,3],[4,5,6]]

C = np.array(c)

print('Numpy array C: \n', C)
print('Shape of C :', C.shape)

Numpy array C: 
 [[1 2 3]
 [4 5 6]]
Shape of C : (2, 3)


### 2.형렬 형태 확인하기 : shape

In [18]:
print('Numpy array A: ', A)     
print('Dimension of A: ', A.ndim)     
print('Shape of A: ', A.shape)     

print('\n')
print('Numpy array C: \n', C)     
print('Dimension of C: ', C.ndim)     
print('Shape of C: ', C.shape)

Numpy array A:  [1. 2. 3.]
Dimension of A:  1
Shape of A:  (3,)


Numpy array C: 
 [[1 2 3]
 [4 5 6]]
Dimension of C:  2
Shape of C:  (2, 3)


#### A 배열은 차원의 갯수가 한 개인 벡터다. 따라서 A 배열의 형태를 튜플로 표현했을 때 원소가 하나 밖에 없다. 형태가 (3, ) 라면 길이가 3인 (열)벡터로 생각하면 된다. 화면에는 가로로 길게 표현되어서 행 벡터로 인식하기 쉽지만 수학에서는 열 벡터를 디폴트다.

##### ※ 형태가 (3, ) 인 벡터와 형태가 (3, 1) 인 행렬은 그 안에 있는 원소들은 동일하지만 엄현이 다른 것이다. 나중에 자신만의 함수를 코딩할 때 리턴값으로 어떤 종류로 리턴해야하는지 고민을 할 경우가 있다. 그럴때는 열 벡터를 선택하는 것이 편하다. <- 물론 나중에 sklearn 이나 Tensorflow 를 사용하면 이런 고민을 할 필요가 없지만...

##### C 배열은 차원의 갯수가 두 개인 행렬이다. 따라서 C 배열의 형태를 튜플로 표현하면 원소가 두 개다. 형태가 (2, 3) 라면 2행 3렬인 행렬을 나타낸다.

### 3. 행렬 형태 바꾸기 : reshape, reshape(-1,1), ravel(), 

In [19]:
print('Numpy array C: \n', C)   

C = C.reshape(3,2)
print('Numpy array C (reshaped to (3,2)): \n', C)   

Numpy array C: 
 [[1 2 3]
 [4 5 6]]
Numpy array C (reshaped to (3,2)): 
 [[1 2]
 [3 4]
 [5 6]]


#### 어떤 행렬을 열 벡터처럼 만드는 이디엄이 있습니다. reshape() 의 인자에 -1 을 써주면 해당 차원의 길이는 나머지 차원 크기에 따라서 결정됩니다.

#### C 행렬을 열 크기가 1인 행렬로 바꿔보겠습니다.

In [21]:
C_colvector = C.reshape(-1,1)   # 행의 크기는 미정이지만 열의 크기는 1로 고정하겠다는 표현입니다.
print(C_colvector)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


#### 위와 같이 열의 크기가 1인 상태로 연산을 해야할 경우도 있지만, 원소들의 정보만 담아서 표현하기에는 Numpy 의 벡터표현이 더 적합합니다. 그럴 때는 ravel() 함수를 사용합니다.

In [27]:
show(C.ravel())

Numpy array a (6,):

[1 2 3 4 5 6]




#### Numpy 배열의 내용과 형태를 출력하는 코드를 자주 사용하니 함수를 만듭니다.

In [29]:
def show(X, name=''):
    print('Numpy array %s %s:\n' % (name,str(X.shape)))
    print(X)
    print('\n')

#### 전치행렬이라고 들어보셨나요?

#### 행렬의 행과 열의 위치를 바꾼행렬을 전치행렬(Transpose matrix)이라고 합니다.

#### m x n 행렬의 전치행렬은 n x m 행렬이 됩니다.

#### Numpy 에서는 간단하게 .T 로 전치행렬을 만들 수 있습니다.

In [30]:
show(C, 'C')
show(C.T, 'Transpose C')

Numpy array C (3, 2):

[[1 2]
 [3 4]
 [5 6]]


Numpy array Transpose C (2, 3):

[[1 3 5]
 [2 4 6]]




### 4. 행렬 데이터 만들기 : arange(), random(), linspace(), logspace()

#### arange( 시작값, 초과하면 안 되는 값, 스텝 ) 과 같은 표현을 사용하면 등차수열에서와 같은 숫자열을 얻을 수 있습니다.

In [55]:
X = np.arange(6); show(X, 'X')     #  np.arange(0,6,1) 과 동일한 표현
Y = np.arange(1,7); show(Y, 'Y')   #  np.arange(1,7,1) 과 동일한 표현

Y = np.arange(1,7).reshape(2,3);  show(Y, 'reshaped Y')   # Numpy 함수를 연속해서 사용할 수 있습니다.

Numpy array X (6,):

[0 1 2 3 4 5]


Numpy array Y (6,):

[1 2 3 4 5 6]


Numpy array reshaped Y (2, 3):

[[1 2 3]
 [4 5 6]]




#### 랜덤값으로 (2,3) 배열을 만들어 봅니다.

In [89]:
np.random.seed(0)
R = np.random.random((2,3)); show(R, 'R')  # 0~1 사이의 랜덤값을 생성해서 Numpy 배열로 만들었습니다

Numpy array R (2, 3):

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]]




#### 표준정규 분포로 부터 랜덤값을 만들 수도 있습니다.

In [98]:
mu = 0.0
sigma = 1.0

G = np.random.normal(mu, sigma, (2,3)); show(G, 'G')  # 0~1 사이의 랜덤값을 생성해서 Numpy 배열로 만들었습니다

Numpy array G (2, 3):

[[-0.02818223  0.42833187  0.06651722]
 [ 0.3024719  -0.63432209 -0.36274117]]




#### 행렬 R 과 G 의 원소 값들의 평균값을 예측해 볼 수 있겠죠?

In [99]:
print('R 의 평균값 : ',R.mean())
print('G 의 평균값 : ',G.mean())

R 의 평균값 :  0.5801997236289743
G 의 평균값 :  -0.03798741622556493


#### 표본의 갯수가 적어서 원하는 값이 나오지 않았습니다.
#### 표본의 갯수를 1000개로 늘려서 다시 평균값을 계산해보겠습니다.

In [100]:
n_data = 1000

R = np.random.random(n_data)
G = np.random.normal(mu, sigma, n_data)    # G 는 Gaussian 에서 따온 것 입니다.

print('R 의 평균값 : ',R.mean())
print('G 의 평균값 : ',G.mean())    

R 의 평균값 :  0.4930680427679857
G 의 평균값 :  0.025120333594165517


#### 예상대로 R 의 평균값은 0.5에 가까워졌고, G의 평균값은 mu = 0.0 와 가까워졌습니다.

### 5. 행렬 데이터의 일부 구간 추출하기

In [101]:
C = np.arange(1,16).reshape(3,5); show(C, 'C')

Numpy array C (3, 5):

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]





3행 5열인 행렬입니다. 1행과 2행을 선택해보겠습니다.

파이썬에서의 인덱스는 0부터 시작하는 것에 주의해야합니다.

slicing 할 때 콜론(:) 을 사용하면 모든 원소를 의미합니다.

In [122]:
C[[0,1], : ]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

행렬의 (2, 3) 위치에 있는 원소값을 골라봅니다. 8을 선택해야합니다.

In [121]:
C[1, 2]

8

행렬의 마지막 행을 선택합니다.

In [104]:
C[ -1, : ]  # '-1' 은 마지막 인덱스를 가르킵니다. Java 에서는  x.length - 1 이렇게 했었죠.

array([11, 12, 13, 14, 15])

In [135]:
C[[-2,-1],:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

그럼 퀴즈를 내보겠습니다.

C 행렬의 마지막 두 행을 추출할 수 있을까요?

이번에는 C 행렬에서 3으로 나눠서 떨어지는 원소들만 모아보겠습니다.

In [105]:
B = C % 3 == 0

이렇게 하면 boolean 타입의 행렬을 얻을 수 있습니다.

In [106]:
show(B,'B')

Numpy array B (3, 5):

[[False False  True False False]
 [ True False False  True False]
 [False  True False False  True]]




B 행렬에는 3으로 나눠서 떨어지는 원소들의 위치 정보가 들어가 있고, 이 정보를 사용해서 C 행렬의 원소들을 불러오면 됩니다.

In [107]:
C[B]

array([ 3,  6,  9, 12, 15])


앞에서 낸 문제는 답 중에 가장 간단한 표현은 다음과 같습니다.

In [108]:
C[:,-2:]     # 마지막 두 개의 열을 추출   C[:, [-2,-1]] 과 같은 표현입니다.

array([[ 4,  5],
       [ 9, 10],
       [14, 15]])

### 6.행렬끼리 더하기, 곱하기, 행렬 원소간의 연산

In [136]:
E = np.arange(1,7).reshape(2,3); show(E,'E')

Numpy array E (2, 3):

[[1 2 3]
 [4 5 6]]





행렬에 스칼라 값을 연산시키면 같은 연산을 행렬의 모든 원소에 적용시킵니다.

In [137]:
E + 1

array([[2, 3, 4],
       [5, 6, 7]])

행렬끼리의 덧셈, 뺼셈은 같은 크기의 행렬끼리만 적용할 수 있습니다. ( 더 정확하게 설명하면 한 쪽 행렬의 어떤 차원을 길이를 정수배로 늘렸을 떄 다른 쪽 행렬과 크기가 같다면 서로 원소끼리의 연산할 수 있습니다.)

In [138]:
E + E

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [146]:
F = np.array([1,2]).reshape(-1,1)
print(F)
E * F   #  E 의 첫 행에는 1을 곱하고 두 번쨰 행에는 2를 곱한 결과을 얻습니다.

[[1]
 [2]]


array([[ 1,  2,  3],
       [ 8, 10, 12]])


행렬끼리의 곱은 A x B 의 경우 행렬 A 의 열이 크기(갯수)와 행렬 B 의 행의 크기가 같아야지 연산할 수 있습니다.

행렬 A 가 (m x n) 행렬이고, 행렬 B 가 (n x k) 행렬이라면 A x B 의 결과는 (m x k) 행렬이 됩니다.

행렬끼리의 곱은 A.dot(B) 또는 A @ B 와 같은 표현을 주로 사용합니다.

In [140]:
H = np.array([1,0,1]).reshape(-1,1)
show(E,'E')
show(H,'H')

Numpy array E (2, 3):

[[1 2 3]
 [4 5 6]]


Numpy array H (3, 1):

[[1]
 [0]
 [1]]




In [141]:
E.dot(H)   

array([[ 4],
       [10]])

In [142]:
E @ H

array([[ 4],
       [10]])

### 7. 행렬끼리 합치기 : hstack(), vstack()

두 행렬의 행의 크기가 같다면 가로 방향으로 붙일 수 있고,

두 행렬의 열의 크기가 같다면 세로 방향으로 붙일 수 있습니다.

In [147]:
np.hstack((E,E))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [148]:
np.vstack((E,E))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

### 8. 그외 연산 : sum(), sqaure(), max(), argmax()


(3 x 3) 행렬을 새로 정의합니다.

In [149]:
S = np.array([3,1,2,4,6,5,8,7,9]).reshape(3,3)
show(S)

Numpy array  (3, 3):

[[3 1 2]
 [4 6 5]
 [8 7 9]]




행렬 원소들의 합

In [150]:
S.sum()  # np.sum(S) 과 같은 표현

45

행렬의 행 방향으로의 합

In [151]:
S.sum(axis=1)

array([ 6, 15, 24])

행렬의 열 방향으로의 합

In [159]:
S.sum(axis=0)  # np.sum(S, axis=0) 와 같은 표현

array([15, 14, 16])

행렬의 각 원소를 제곱해서 합을 구함

In [152]:
np.square(S).sum()

285


이번에는 최대값, 최소값에 관한 정보를 얻어보겠습니다.

행렬의 전체 원소 중에서 최대값

In [153]:
S.max()

9

행렬의 각 행에서의 최대값

In [154]:
S.max(axis=1)

array([3, 6, 9])

행렬의 각 열에서의 최대값

In [155]:
S.max(axis=0)

array([8, 7, 9])

행렬의 각 행에서의 최대값인 원소의 열 위치

In [157]:
S.argmax(axis=1)

array([0, 1, 2], dtype=int64)

행렬의 각 열에서의 최대값인 원소의 행 위치

In [158]:
S.argmax(axis=0)

array([2, 2, 2], dtype=int64)